# Generated by Django 3.2.4 on 2021-07-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelinktoproject',
            name='member_invite',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='projects.projectmember', verbose_name='Приглашающий'),
        ),
    ]
