# Generated by Django 3.2.4 on 2021-07-19 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitelinktoproject',
            name='link',
        ),
        migrations.RemoveField(
            model_name='invitelinktoproject',
            name='slug',
        ),
        migrations.AddField(
            model_name='invitelinktoproject',
            name='link_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
