# Generated by Django 3.2.4 on 2021-06-12 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('accounts', '0003_alter_user_active_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
